name: todo
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  copy_with_extension: ^5.0.3
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.7.5
  copy_with_extension_gen: ^5.0.3
  build_runner: ^2.4.5

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900

        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700

        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500

        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
          weight: 500

        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400

        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300

        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 100

        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic

  assets:
    - assets/icons/